# Generated by Django 2.1.3 on 2018-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='hiring_partner',
        ),
        migrations.RenameField(
            model_name='partner_profile',
            old_name='Partner_name',
            new_name='partner_name',
        ),
        migrations.AlterField(
            model_name='partner_profile',
            name='partner_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
